apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupon
  template:
    metadata:
      labels:
        app: coupon
    spec:
      containers:
        - name: coupon
          image: hiranyap/ayurmart-microservice-coupon     
          ports:
            - containerPort: 7003
          env:
              - name: PORT
                value: "7003"
          envFrom:
            - secretRef:
                name: ayurmart-secrets
---

apiVersion: v1
kind: Service
metadata:
  name: coupon-service
spec:
  selector:
    app: coupon
  ports:
    - name: http
      protocol: TCP
      port: 7003
      targetPort: 7003
  type: NodePort